/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobCampusRouteImport } from './routes/job-campus'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CounselorRouteImport } from './routes/counselor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingsIndexRouteImport } from './routes/trainings/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as InternshipsIndexRouteImport } from './routes/internships/index'
import { Route as TrainingsIdRouteImport } from './routes/trainings/$id'
import { Route as TrainingLoginRouteImport } from './routes/training/login'
import { Route as SalesLoginRouteImport } from './routes/sales/login'
import { Route as ProgramsSlugRouteImport } from './routes/programs/$slug'
import { Route as InternshipsIdRouteImport } from './routes/internships/$id'
import { Route as InternshipLoginRouteImport } from './routes/internship/login'
import { Route as DashboardTrainingRouteImport } from './routes/dashboard/training'
import { Route as DashboardSalesRouteImport } from './routes/dashboard/sales'
import { Route as DashboardInboxRouteImport } from './routes/dashboard/inbox'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard/certificates'
import { Route as DashboardCandidateRouteImport } from './routes/dashboard/candidate'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApplyIdRouteImport } from './routes/apply/$id'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard/student/index'
import { Route as TrainingsIdRegisterRouteImport } from './routes/trainings_.$id.register'
import { Route as DashboardStudentTrainingsRouteImport } from './routes/dashboard/student/trainings'
import { Route as DashboardStudentProfileRouteImport } from './routes/dashboard/student/profile'
import { Route as DashboardStudentPaymentsRouteImport } from './routes/dashboard/student/payments'
import { Route as DashboardStudentOfferLetterRouteImport } from './routes/dashboard/student/offer-letter'
import { Route as DashboardStudentLecturesRouteImport } from './routes/dashboard/student/lectures'
import { Route as DashboardStudentFaceRegisterRouteImport } from './routes/dashboard/student/face-register'
import { Route as DashboardStudentCertificateRouteImport } from './routes/dashboard/student/certificate'
import { Route as DashboardStudentAttendanceRouteImport } from './routes/dashboard/student/attendance'
import { Route as DashboardStudentAssignmentsRouteImport } from './routes/dashboard/student/assignments'
import { Route as DashboardStudentSecureAssignmentIdRouteImport } from './routes/dashboard/student/secure-assignment.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobCampusRoute = JobCampusRouteImport.update({
  id: '/job-campus',
  path: '/job-campus',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselorRoute = CounselorRouteImport.update({
  id: '/counselor',
  path: '/counselor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIndexRoute = TrainingsIndexRouteImport.update({
  id: '/trainings/',
  path: '/trainings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsIndexRoute = InternshipsIndexRouteImport.update({
  id: '/internships/',
  path: '/internships/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIdRoute = TrainingsIdRouteImport.update({
  id: '/trainings/$id',
  path: '/trainings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingLoginRoute = TrainingLoginRouteImport.update({
  id: '/training/login',
  path: '/training/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLoginRoute = SalesLoginRouteImport.update({
  id: '/sales/login',
  path: '/sales/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsIdRoute = InternshipsIdRouteImport.update({
  id: '/internships/$id',
  path: '/internships/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipLoginRoute = InternshipLoginRouteImport.update({
  id: '/internship/login',
  path: '/internship/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrainingRoute = DashboardTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCandidateRoute = DashboardCandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApplyIdRoute = ApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => DashboardRoute,
} as any)
const TrainingsIdRegisterRoute = TrainingsIdRegisterRouteImport.update({
  id: '/trainings_/$id/register',
  path: '/trainings/$id/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentTrainingsRoute =
  DashboardStudentTrainingsRouteImport.update({
    id: '/student/trainings',
    path: '/student/trainings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentProfileRoute = DashboardStudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentPaymentsRoute =
  DashboardStudentPaymentsRouteImport.update({
    id: '/student/payments',
    path: '/student/payments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentOfferLetterRoute =
  DashboardStudentOfferLetterRouteImport.update({
    id: '/student/offer-letter',
    path: '/student/offer-letter',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentLecturesRoute =
  DashboardStudentLecturesRouteImport.update({
    id: '/student/lectures',
    path: '/student/lectures',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentFaceRegisterRoute =
  DashboardStudentFaceRegisterRouteImport.update({
    id: '/student/face-register',
    path: '/student/face-register',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentCertificateRoute =
  DashboardStudentCertificateRouteImport.update({
    id: '/student/certificate',
    path: '/student/certificate',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentAttendanceRoute =
  DashboardStudentAttendanceRouteImport.update({
    id: '/student/attendance',
    path: '/student/attendance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentAssignmentsRoute =
  DashboardStudentAssignmentsRouteImport.update({
    id: '/student/assignments',
    path: '/student/assignments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentSecureAssignmentIdRoute =
  DashboardStudentSecureAssignmentIdRouteImport.update({
    id: '/student/secure-assignment/$id',
    path: '/student/secure-assignment/$id',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/counselor': typeof CounselorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/job-campus': typeof JobCampusRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/apply/$id': typeof ApplyIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/candidate': typeof DashboardCandidateRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/internship/login': typeof InternshipLoginRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/sales/login': typeof SalesLoginRoute
  '/training/login': typeof TrainingLoginRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/internships/': typeof InternshipsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/trainings/': typeof TrainingsIndexRoute
  '/dashboard/student/assignments': typeof DashboardStudentAssignmentsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/certificate': typeof DashboardStudentCertificateRoute
  '/dashboard/student/face-register': typeof DashboardStudentFaceRegisterRoute
  '/dashboard/student/lectures': typeof DashboardStudentLecturesRoute
  '/dashboard/student/offer-letter': typeof DashboardStudentOfferLetterRoute
  '/dashboard/student/payments': typeof DashboardStudentPaymentsRoute
  '/dashboard/student/profile': typeof DashboardStudentProfileRoute
  '/dashboard/student/trainings': typeof DashboardStudentTrainingsRoute
  '/trainings/$id/register': typeof TrainingsIdRegisterRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/student/secure-assignment/$id': typeof DashboardStudentSecureAssignmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/counselor': typeof CounselorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/job-campus': typeof JobCampusRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/apply/$id': typeof ApplyIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/candidate': typeof DashboardCandidateRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/internship/login': typeof InternshipLoginRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/sales/login': typeof SalesLoginRoute
  '/training/login': typeof TrainingLoginRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/internships': typeof InternshipsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/trainings': typeof TrainingsIndexRoute
  '/dashboard/student/assignments': typeof DashboardStudentAssignmentsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/certificate': typeof DashboardStudentCertificateRoute
  '/dashboard/student/face-register': typeof DashboardStudentFaceRegisterRoute
  '/dashboard/student/lectures': typeof DashboardStudentLecturesRoute
  '/dashboard/student/offer-letter': typeof DashboardStudentOfferLetterRoute
  '/dashboard/student/payments': typeof DashboardStudentPaymentsRoute
  '/dashboard/student/profile': typeof DashboardStudentProfileRoute
  '/dashboard/student/trainings': typeof DashboardStudentTrainingsRoute
  '/trainings/$id/register': typeof TrainingsIdRegisterRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
  '/dashboard/student/secure-assignment/$id': typeof DashboardStudentSecureAssignmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/counselor': typeof CounselorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/job-campus': typeof JobCampusRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sales': typeof AdminSalesRoute
  '/apply/$id': typeof ApplyIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/candidate': typeof DashboardCandidateRoute
  '/dashboard/certificates': typeof DashboardCertificatesRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/dashboard/training': typeof DashboardTrainingRoute
  '/internship/login': typeof InternshipLoginRoute
  '/internships/$id': typeof InternshipsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/sales/login': typeof SalesLoginRoute
  '/training/login': typeof TrainingLoginRoute
  '/trainings/$id': typeof TrainingsIdRoute
  '/internships/': typeof InternshipsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/trainings/': typeof TrainingsIndexRoute
  '/dashboard/student/assignments': typeof DashboardStudentAssignmentsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/certificate': typeof DashboardStudentCertificateRoute
  '/dashboard/student/face-register': typeof DashboardStudentFaceRegisterRoute
  '/dashboard/student/lectures': typeof DashboardStudentLecturesRoute
  '/dashboard/student/offer-letter': typeof DashboardStudentOfferLetterRoute
  '/dashboard/student/payments': typeof DashboardStudentPaymentsRoute
  '/dashboard/student/profile': typeof DashboardStudentProfileRoute
  '/dashboard/student/trainings': typeof DashboardStudentTrainingsRoute
  '/trainings_/$id/register': typeof TrainingsIdRegisterRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/student/secure-assignment/$id': typeof DashboardStudentSecureAssignmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/counselor'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/job-campus'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify'
    | '/admin/login'
    | '/admin/sales'
    | '/apply/$id'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/candidate'
    | '/dashboard/certificates'
    | '/dashboard/inbox'
    | '/dashboard/sales'
    | '/dashboard/training'
    | '/internship/login'
    | '/internships/$id'
    | '/programs/$slug'
    | '/sales/login'
    | '/training/login'
    | '/trainings/$id'
    | '/internships/'
    | '/programs/'
    | '/trainings/'
    | '/dashboard/student/assignments'
    | '/dashboard/student/attendance'
    | '/dashboard/student/certificate'
    | '/dashboard/student/face-register'
    | '/dashboard/student/lectures'
    | '/dashboard/student/offer-letter'
    | '/dashboard/student/payments'
    | '/dashboard/student/profile'
    | '/dashboard/student/trainings'
    | '/trainings/$id/register'
    | '/dashboard/student/'
    | '/dashboard/student/secure-assignment/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/counselor'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/job-campus'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify'
    | '/admin/login'
    | '/admin/sales'
    | '/apply/$id'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/candidate'
    | '/dashboard/certificates'
    | '/dashboard/inbox'
    | '/dashboard/sales'
    | '/dashboard/training'
    | '/internship/login'
    | '/internships/$id'
    | '/programs/$slug'
    | '/sales/login'
    | '/training/login'
    | '/trainings/$id'
    | '/internships'
    | '/programs'
    | '/trainings'
    | '/dashboard/student/assignments'
    | '/dashboard/student/attendance'
    | '/dashboard/student/certificate'
    | '/dashboard/student/face-register'
    | '/dashboard/student/lectures'
    | '/dashboard/student/offer-letter'
    | '/dashboard/student/payments'
    | '/dashboard/student/profile'
    | '/dashboard/student/trainings'
    | '/trainings/$id/register'
    | '/dashboard/student'
    | '/dashboard/student/secure-assignment/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/counselor'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/job-campus'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify'
    | '/admin/login'
    | '/admin/sales'
    | '/apply/$id'
    | '/blog/$slug'
    | '/dashboard/admin'
    | '/dashboard/candidate'
    | '/dashboard/certificates'
    | '/dashboard/inbox'
    | '/dashboard/sales'
    | '/dashboard/training'
    | '/internship/login'
    | '/internships/$id'
    | '/programs/$slug'
    | '/sales/login'
    | '/training/login'
    | '/trainings/$id'
    | '/internships/'
    | '/programs/'
    | '/trainings/'
    | '/dashboard/student/assignments'
    | '/dashboard/student/attendance'
    | '/dashboard/student/certificate'
    | '/dashboard/student/face-register'
    | '/dashboard/student/lectures'
    | '/dashboard/student/offer-letter'
    | '/dashboard/student/payments'
    | '/dashboard/student/profile'
    | '/dashboard/student/trainings'
    | '/trainings_/$id/register'
    | '/dashboard/student/'
    | '/dashboard/student/secure-assignment/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CounselorRoute: typeof CounselorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobCampusRoute: typeof JobCampusRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSalesRoute: typeof AdminSalesRoute
  ApplyIdRoute: typeof ApplyIdRoute
  InternshipLoginRoute: typeof InternshipLoginRoute
  InternshipsIdRoute: typeof InternshipsIdRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  SalesLoginRoute: typeof SalesLoginRoute
  TrainingLoginRoute: typeof TrainingLoginRoute
  TrainingsIdRoute: typeof TrainingsIdRoute
  InternshipsIndexRoute: typeof InternshipsIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  TrainingsIndexRoute: typeof TrainingsIndexRoute
  TrainingsIdRegisterRoute: typeof TrainingsIdRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-campus': {
      id: '/job-campus'
      path: '/job-campus'
      fullPath: '/job-campus'
      preLoaderRoute: typeof JobCampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselor': {
      id: '/counselor'
      path: '/counselor'
      fullPath: '/counselor'
      preLoaderRoute: typeof CounselorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/': {
      id: '/trainings/'
      path: '/trainings'
      fullPath: '/trainings/'
      preLoaderRoute: typeof TrainingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/': {
      id: '/internships/'
      path: '/internships'
      fullPath: '/internships/'
      preLoaderRoute: typeof InternshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/$id': {
      id: '/trainings/$id'
      path: '/trainings/$id'
      fullPath: '/trainings/$id'
      preLoaderRoute: typeof TrainingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/login': {
      id: '/training/login'
      path: '/training/login'
      fullPath: '/training/login'
      preLoaderRoute: typeof TrainingLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/login': {
      id: '/sales/login'
      path: '/sales/login'
      fullPath: '/sales/login'
      preLoaderRoute: typeof SalesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/$id': {
      id: '/internships/$id'
      path: '/internships/$id'
      fullPath: '/internships/$id'
      preLoaderRoute: typeof InternshipsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internship/login': {
      id: '/internship/login'
      path: '/internship/login'
      fullPath: '/internship/login'
      preLoaderRoute: typeof InternshipLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/training': {
      id: '/dashboard/training'
      path: '/training'
      fullPath: '/dashboard/training'
      preLoaderRoute: typeof DashboardTrainingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sales': {
      id: '/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/candidate': {
      id: '/dashboard/candidate'
      path: '/candidate'
      fullPath: '/dashboard/candidate'
      preLoaderRoute: typeof DashboardCandidateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/apply/$id': {
      id: '/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof ApplyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/student'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/trainings_/$id/register': {
      id: '/trainings_/$id/register'
      path: '/trainings/$id/register'
      fullPath: '/trainings/$id/register'
      preLoaderRoute: typeof TrainingsIdRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student/trainings': {
      id: '/dashboard/student/trainings'
      path: '/student/trainings'
      fullPath: '/dashboard/student/trainings'
      preLoaderRoute: typeof DashboardStudentTrainingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/profile': {
      id: '/dashboard/student/profile'
      path: '/student/profile'
      fullPath: '/dashboard/student/profile'
      preLoaderRoute: typeof DashboardStudentProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/payments': {
      id: '/dashboard/student/payments'
      path: '/student/payments'
      fullPath: '/dashboard/student/payments'
      preLoaderRoute: typeof DashboardStudentPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/offer-letter': {
      id: '/dashboard/student/offer-letter'
      path: '/student/offer-letter'
      fullPath: '/dashboard/student/offer-letter'
      preLoaderRoute: typeof DashboardStudentOfferLetterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/lectures': {
      id: '/dashboard/student/lectures'
      path: '/student/lectures'
      fullPath: '/dashboard/student/lectures'
      preLoaderRoute: typeof DashboardStudentLecturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/face-register': {
      id: '/dashboard/student/face-register'
      path: '/student/face-register'
      fullPath: '/dashboard/student/face-register'
      preLoaderRoute: typeof DashboardStudentFaceRegisterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/certificate': {
      id: '/dashboard/student/certificate'
      path: '/student/certificate'
      fullPath: '/dashboard/student/certificate'
      preLoaderRoute: typeof DashboardStudentCertificateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/attendance': {
      id: '/dashboard/student/attendance'
      path: '/student/attendance'
      fullPath: '/dashboard/student/attendance'
      preLoaderRoute: typeof DashboardStudentAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/assignments': {
      id: '/dashboard/student/assignments'
      path: '/student/assignments'
      fullPath: '/dashboard/student/assignments'
      preLoaderRoute: typeof DashboardStudentAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/student/secure-assignment/$id': {
      id: '/dashboard/student/secure-assignment/$id'
      path: '/student/secure-assignment/$id'
      fullPath: '/dashboard/student/secure-assignment/$id'
      preLoaderRoute: typeof DashboardStudentSecureAssignmentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCandidateRoute: typeof DashboardCandidateRoute
  DashboardCertificatesRoute: typeof DashboardCertificatesRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardSalesRoute: typeof DashboardSalesRoute
  DashboardTrainingRoute: typeof DashboardTrainingRoute
  DashboardStudentAssignmentsRoute: typeof DashboardStudentAssignmentsRoute
  DashboardStudentAttendanceRoute: typeof DashboardStudentAttendanceRoute
  DashboardStudentCertificateRoute: typeof DashboardStudentCertificateRoute
  DashboardStudentFaceRegisterRoute: typeof DashboardStudentFaceRegisterRoute
  DashboardStudentLecturesRoute: typeof DashboardStudentLecturesRoute
  DashboardStudentOfferLetterRoute: typeof DashboardStudentOfferLetterRoute
  DashboardStudentPaymentsRoute: typeof DashboardStudentPaymentsRoute
  DashboardStudentProfileRoute: typeof DashboardStudentProfileRoute
  DashboardStudentTrainingsRoute: typeof DashboardStudentTrainingsRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
  DashboardStudentSecureAssignmentIdRoute: typeof DashboardStudentSecureAssignmentIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCandidateRoute: DashboardCandidateRoute,
  DashboardCertificatesRoute: DashboardCertificatesRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardSalesRoute: DashboardSalesRoute,
  DashboardTrainingRoute: DashboardTrainingRoute,
  DashboardStudentAssignmentsRoute: DashboardStudentAssignmentsRoute,
  DashboardStudentAttendanceRoute: DashboardStudentAttendanceRoute,
  DashboardStudentCertificateRoute: DashboardStudentCertificateRoute,
  DashboardStudentFaceRegisterRoute: DashboardStudentFaceRegisterRoute,
  DashboardStudentLecturesRoute: DashboardStudentLecturesRoute,
  DashboardStudentOfferLetterRoute: DashboardStudentOfferLetterRoute,
  DashboardStudentPaymentsRoute: DashboardStudentPaymentsRoute,
  DashboardStudentProfileRoute: DashboardStudentProfileRoute,
  DashboardStudentTrainingsRoute: DashboardStudentTrainingsRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
  DashboardStudentSecureAssignmentIdRoute:
    DashboardStudentSecureAssignmentIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CounselorRoute: CounselorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobCampusRoute: JobCampusRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSalesRoute: AdminSalesRoute,
  ApplyIdRoute: ApplyIdRoute,
  InternshipLoginRoute: InternshipLoginRoute,
  InternshipsIdRoute: InternshipsIdRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  SalesLoginRoute: SalesLoginRoute,
  TrainingLoginRoute: TrainingLoginRoute,
  TrainingsIdRoute: TrainingsIdRoute,
  InternshipsIndexRoute: InternshipsIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  TrainingsIndexRoute: TrainingsIndexRoute,
  TrainingsIdRegisterRoute: TrainingsIdRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
