import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/hooks/use-auth";
import { ShieldCheck, Printer, ArrowLeft, Award, BadgeCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/dashboard/student/certificate")({
  component: CertificatePage,
});

function CertificatePage() {
  const { user } = useAuth();
  const [student, setStudent] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user?.id) {
      fetchStudentData();
    }
  }, [user]);

  async function fetchStudentData() {
    try {
      const { data, error } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", user?.id)
        .maybeSingle();

      if (data) {
        setStudent(data);
      }
    } catch (err) {
      console.error("Error loading student details:", err);
    } finally {
      setLoading(false);
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-navy"></div>
      </div>
    );
  }

  const today = new Date().toLocaleDateString("en-US", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const durationStr = student?.internship_duration || "8 Weeks";
  const certId = `UGC/OFFER/${student?.university_roll_number?.slice(-4) || "0000"}/${new Date(student?.created_at || Date.now()).getFullYear()}`;

  if (student && !student.certificate_generated) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center text-center p-6 space-y-4">
        <Award size={64} className="text-slate-300" />
        <h2 className="text-2xl font-black text-navy-deep uppercase tracking-tighter">Certificate Pending</h2>
        <p className="text-muted-foreground max-w-md">Your certificate has not been generated by the administration yet. Please complete all requirements and wait for the official issuance.</p>
        <Button asChild variant="outline" className="mt-4"><Link to="/dashboard/student">Back to Dashboard</Link></Button>
      </div>
    );
  }

  return (
    <div className="space-y-6 pb-12 print:p-0 print:m-0">
      {/* ACTION BAR */}
      <div className="flex items-center justify-between gap-4 border-b pb-4 print:hidden">
        <div className="flex items-center gap-2">
          <Button asChild variant="ghost" size="sm" className="h-9 rounded-xl font-bold gap-2 text-muted-foreground hover:text-navy">
            <Link to="/dashboard/student">
              <ArrowLeft size={16} /> Back to Dashboard
            </Link>
          </Button>
        </div>
        <div className="flex gap-3">
          <Button onClick={() => window.print()} className="bg-navy hover:bg-navy-deep text-white font-black text-xs uppercase tracking-widest h-11 px-6 rounded-xl gap-2 shadow-lg shadow-navy/20">
            <Printer size={16} /> Print Certificate
          </Button>
        </div>
      </div>

      {/* LANDSCAPE CERTIFICATE CONTAINER */}
      <div className="flex justify-center items-center w-full overflow-x-auto py-6 print:py-0 print:bg-white">
        <div 
          id="certificate-container" 
          className="w-[1050px] h-[740px] bg-white p-12 shadow-2xl relative border-[12px] border-double border-navy flex flex-col justify-between items-center text-center select-none print:shadow-none print:m-0 print:w-full print:h-[720px] print:border-[10px]"
          style={{ boxSizing: "border-box" }}
        >
          {/* WATERMARK BACKGROUND */}
          <div className="absolute inset-0 opacity-[0.02] flex items-center justify-center pointer-events-none z-0">
            <Award size={450} className="text-navy" />
          </div>

          {/* INNER BORDER */}
          <div className="absolute inset-2 border-2 border-gold/40 pointer-events-none z-10"></div>

          {/* TOP HEADER */}
          <div className="w-full flex justify-between items-start relative z-20">
            <div className="text-left">
              <span className="text-[10px] font-black text-gold uppercase tracking-[0.25em] block mb-1">Aligned Verification ID</span>
              <span className="font-mono text-xs font-bold text-navy-deep bg-slate-100 px-3 py-1 rounded-md border">{certId}</span>
            </div>
            <div className="text-right">
              <span className="text-[10px] font-black text-gold uppercase tracking-[0.25em] block mb-1">Security Standard</span>
              <span className="text-[9px] font-black text-navy border border-navy/30 px-2 py-0.5 rounded bg-white">ISO 9001:2015 · AICTE · BSDM</span>
            </div>
          </div>

          {/* MAIN CERTIFICATE DETAILS */}
          <div className="space-y-4 max-w-4xl relative z-20 mt-4">
            <div className="flex justify-center mb-1">
              <Award className="text-gold size-14 animate-pulse" />
            </div>
            <h1 className="font-display text-4xl font-black text-navy-deep uppercase tracking-[0.15em]">
              Certificate of Completion
            </h1>
            <div className="h-0.5 w-60 bg-gold mx-auto my-3 relative">
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-white px-2">
                <BadgeCheck className="text-gold size-5" />
              </div>
            </div>
            
            <p className="text-sm font-medium text-slate-500 italic uppercase tracking-[0.1em] mt-2">
              This is proudly presented to
            </p>
            
            {/* STUDENT NAME */}
            <h2 className="text-4xl md:text-5xl font-black font-display text-navy-deep underline decoration-gold/40 underline-offset-8 decoration-2 capitalize tracking-wide py-2">
              {student?.full_name || "STUDENT NAME"}
            </h2>

            {/* STAGED DETAILS STATEMENT */}
            <div className="text-sm text-slate-700 leading-relaxed max-w-3xl mx-auto space-y-3 font-medium px-4 mt-4">
              <p>
                for successfully completing a structured technical internship program in the domain of{" "}
                <span className="font-black text-navy-deep text-base underline decoration-gold/60">{student?.program || student?.department || "Software Engineering"}</span>.
              </p>
              <p className="text-slate-600 text-xs">
                Institution: <span className="font-bold text-navy-deep">{student?.college_name || "COLLEGE NAME"}</span> 
                <span className="mx-2 text-slate-300">|</span> 
                University: <span className="font-bold text-navy-deep">{student?.university_name || "UNIVERSITY NAME"}</span>
              </p>
              <p className="text-slate-600 text-xs">
                Department: <span className="font-bold text-navy-deep">{student?.department || "BRANCH"}</span>
                <span className="mx-2 text-slate-300">|</span> 
                Degree: <span className="font-bold text-navy-deep">{student?.degree || "DEGREE"}</span>
                <span className="mx-2 text-slate-300">|</span> 
                University Roll No: <span className="font-mono font-bold text-gold">{student?.university_roll_number || "ROLL NUMBER"}</span>
              </p>
              <p className="text-slate-600 text-xs">
                The candidate has fully satisfied all project milestones, assignments, and training requirements over a formal program duration of{" "}
                <span className="font-bold text-navy-deep bg-slate-100 px-2 py-0.5 rounded">{durationStr}</span>.
              </p>
            </div>
          </div>

          {/* BOTTOM SIGNATURE SECTION */}
          <div className="w-full grid grid-cols-3 items-end mt-8 relative z-20">
            {/* LEFT: ISSUING AUTHORITY */}
            <div className="flex flex-col items-center">
              <div className="text-xs font-black text-navy-deep font-mono mb-1">UGC INTERN</div>
              <div className="h-px w-36 bg-slate-300 my-1"></div>
              <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Director, UGC Connect</span>
            </div>

            {/* CENTER: VERIFIED GOLD BADGE */}
            <div className="flex flex-col items-center justify-center">
              <div className="size-20 rounded-full border-4 border-gold/40 flex flex-col items-center justify-center bg-gold/5 relative p-1 shadow-inner">
                <ShieldCheck className="text-gold size-8" />
                <span className="text-[7px] font-black text-navy-deep uppercase tracking-tighter mt-0.5">VERIFIED</span>
              </div>
              <span className="text-[8px] font-black text-slate-400 uppercase tracking-wider mt-2">Issued: {today}</span>
            </div>

            {/* RIGHT: INSTITUTION SIGNATURE */}
            <div className="flex flex-col items-center">
              <div className="text-xs font-black text-navy-deep font-mono mb-1">BSDM / BOARD</div>
              <div className="h-px w-36 bg-slate-300 my-1"></div>
              <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Authorized Coordinator</span>
            </div>
          </div>

          {/* STYLIZED CERTIFICATE FOOTER */}
          <div className="w-full text-center text-[7px] font-bold text-slate-400 uppercase tracking-widest border-t border-slate-100 pt-4 mt-2">
            This is a system generated authenticated credential. Scan Verification ID on our public verification portal to inspect record.
          </div>
        </div>
      </div>

      {/* PRINT-ONLY CSS OVERRIDES */}
      <style>{`
        @media print {
          body * {
            visibility: hidden;
          }
          #certificate-container, #certificate-container * {
            visibility: visible;
          }
          #certificate-container {
            position: absolute;
            left: 0;
            top: 0;
            width: 100% !important;
            height: 100% !important;
            border: 10px double #0d1e3d !important;
            box-shadow: none !important;
            transform: scale(1) !important;
            margin: 0 !important;
            padding: 24px !important;
            box-sizing: border-box !important;
            page-break-inside: avoid !important;
          }
          @page {
            size: landscape;
            margin: 0;
          }
        }
      `}</style>
    </div>
  );
}
